language: go
go:
  - "1.13"

cache:
  directories:
  - /home/travis/gopath/bin

install:
  - bash --version
  - pwd
  - cd ../../..
  - mkdir -p knative.dev
  - mv github.com/adrcunha/test-infra knative.dev
  - cd knative.dev/test-infra
  - [[ -z "$(which ko)" ]] && GO111MODULE=on go get github.com/google/ko/cmd/ko
  - [[ -z "$(which kail)" ]] && GO111MODULE=on go get github.com/boz/kail/cmd/kail
  - [[ -z "$(which dep)" ]] && go get -u github.com/golang/dep/cmd/dep
  - [[ -z "$(which go-junit-report)" ]] && go get -u github.com/jstemmer/go-junit-report
  - [[ -z "$(which liche)" ]] && GO111MODULE=on go get -u github.com/raviqqe/liche

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/1.2.0/bazel_1.2.0-linux-x86_64.deb
  - sudo dpkg -i bazel_1.2.0-linux-x86_64.deb

jobs:
  include:
  - name: "Build tests"
    env: TEST_SUITE="--build-tests"
  - name: "Unit tests"
    env: TEST_SUITE="--unit-tests"

script: ./test/presubmit-tests.sh $TEST_SUITE
