language: go
go:
  - "1.13"

env:
  global:
    - secure: HNHiMV6n/F7SuqdG1AmjtYxghqd9ky4Lanv7kLyQKE6lx+W4Hl7Vyx6IB8vZyaPreHsYvH5MN7HriB1tr4vkEpEVy0gdHOkg17X4cU92NItvleQCzUceSvrWDl5kiFEjQmFIr5+PI/sPb6SPpG68d8wcIzu6WuMjacBxNvfWaJptkwn7Ovs6MliLUNgrYfd5/11EAIuwp3GqppUCby9Fpm/3RO7X8Xsdp4wINqWiMpM+7Vi98h5bfLHMf4m0p/yITx+Xh6l9rtRJVYQXKirqVcfaG/roj14OkzS6F2kRNP9dsQmcV3BobTMSyJrUbLD38Rid4NNFbhd9BuENos+tdBWE3oYvbXLUWtTFx/DXUjV7iK1fz4iAbAXYug3op6838F8Z5+GiCBmsbRBtrUzdNxUGiuo++Z3Fy2xHyV5vlnYhlAW+x5dBcFTikbdrGNSbTJGeDKUADlpkwzHvt1GHZwopkO+bDNr1EDE6MqlcJA/E9cFI0HnPqFuu0k7rTVksRK0NjHVKouYhPWpyugWu3RtZmhYiW92+8TtLh39z31fEcEJxIrCksXpVvAX2S/NhlrvhidZS1hEl4acnG/mqOw7OzV1zT8EwqDsH2LCsCIR5GpU8MvAkCDd8m0fLAM5P0+d8DV/6l7FIuua9cBzdrYaY3DXO+/6CjphpsTB3CQM=

cache:
  directories:
  - /home/travis/gopath/bin

# This can be moved to a script in the repo.
install:
  - bash --version
  - pwd
  - cd ../../..
  - mkdir -p knative.dev
  - mv github.com/adrcunha/test-infra knative.dev
  - cd knative.dev/test-infra
  - echo -e "Encrypted env var.\nSOMEVAR=secretvalue\nSOMEVAR=${SOMEVAR}\n---"
  - if [[ -z "$(which ko)" ]]; then GO111MODULE=on go get github.com/google/ko/cmd/ko ; fi
  - if [[ -z "$(which kail)" ]]; then GO111MODULE=on go get github.com/boz/kail/cmd/kail ; fi
  - if [[ -z "$(which dep)" ]]; then go get -u github.com/golang/dep/cmd/dep ; fi
  - if [[ -z "$(which go-junit-report)" ]]; then go get -u github.com/jstemmer/go-junit-report ; fi
  - if [[ -z "$(which liche)" ]]; then GO111MODULE=on go get -u github.com/raviqqe/liche ; fi
  - if [[ -z "$(which kubectl)" ]]; then curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl ; chmod +x ./kubectl ; sudo mv ./kubectl /usr/local/bin/kubectl ; fi
  - if [[ -z "$(which goveralls)" ]]; then go get github.com/mattn/goveralls ; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/1.2.0/bazel_1.2.0-linux-x86_64.deb
  - sudo dpkg -i bazel_1.2.0-linux-x86_64.deb

jobs:
  include:
  - name: "Code coverage"
    env: TEST_SUITE="--code-coverage"
  - name: "Build tests"
    env: TEST_SUITE="--build-tests"
  - name: "Unit tests"
    env: TEST_SUITE="--unit-tests"

script: if [[ $TEST_SUITE == --code-coverage ]]; then $GOPATH/bin/goveralls -service=travis-ci ; else ./test/presubmit-tests.sh $TEST_SUITE ; fi
