language: go
go:
  - "1.13"

cache:
  directories:
  - /home/travis/gopath/bin

# This can be moved to a script in the repo.
install:
  - bash --version
  - pwd
  - cd ../../..
  - mkdir -p knative.dev
  - mv github.com/adrcunha/test-infra knative.dev
  - cd knative.dev/test-infra
  - if [[ -z "$(which ko)" ]]; then GO111MODULE=on go get github.com/google/ko/cmd/ko ; fi
  - if [[ -z "$(which kail)" ]]; then GO111MODULE=on go get github.com/boz/kail/cmd/kail ; fi
  - if [[ -z "$(which dep)" ]]; then go get -u github.com/golang/dep/cmd/dep ; fi
  - if [[ -z "$(which go-junit-report)" ]]; then go get -u github.com/jstemmer/go-junit-report ; fi
  - if [[ -z "$(which liche)" ]]; then GO111MODULE=on go get -u github.com/raviqqe/liche ; fi
  - if [[ -z "$(which kubectl)" ]]; then curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl ; chmod +x ./kubectl ; sudo mv ./kubectl /usr/local/bin/kubectl ; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/1.2.0/bazel_1.2.0-linux-x86_64.deb
  - sudo dpkg -i bazel_1.2.0-linux-x86_64.deb

jobs:
  include:
  - name: "Build tests"
    env: TEST_SUITE="--build-tests"
  - name: "Unit tests"
    env: TEST_SUITE="--unit-tests"

script: ./test/presubmit-tests.sh $TEST_SUITE
