language: go
go:
  - "1.13"

install:
  - pwd
  - cd ../../..
  - mkdir -p knative.dev
  - mv github.com/adrcunha/test-infra knative.dev
  - cd knative.dev/test-infra
  - GO111MODULE=on go get github.com/google/ko/cmd/ko
  - GO111MODULE=on go get github.com/boz/kail/cmd/kail
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/jstemmer/go-junit-report
  - GO111MODULE=on go get -u github.com/raviqqe/liche

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/1.2.0/bazel_1.2.0-linux-x86_64.deb
#  - sha256sum -c tools/bazel_1.2.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_1.2.0-linux-x86_64.deb

script: ./test/presubmit-tests.sh --build-tests
